# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lightView.ui'
#
# Created: Wed Apr 13 12:24:03 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_lightView(object):
    def setupUi(self, lightView):
        lightView.setObjectName("lightView")
        lightView.resize(654, 393)
        self.mainWidgetLight = QtGui.QWidget(lightView)
        self.mainWidgetLight.setObjectName("mainWidgetLight")
        self.tableView = QtGui.QTableView(self.mainWidgetLight)
        self.tableView.setGeometry(QtCore.QRect(5, 1, 641, 361))
        self.tableView.setObjectName("tableView")
        self.gridLayoutWidget = QtGui.QWidget(self.mainWidgetLight)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 631, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.lightLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.lightLayout.setSpacing(0)
        self.lightLayout.setContentsMargins(0, 0, 0, 0)
        self.lightLayout.setObjectName("lightLayout")
        self.front_label = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.front_label.setFont(font)
        self.front_label.setStyleSheet("#front_label{background-color: #0CB90C;}")
        self.front_label.setFrameShape(QtGui.QFrame.Box)
        self.front_label.setAlignment(QtCore.Qt.AlignCenter)
        self.front_label.setObjectName("front_label")
        self.lightLayout.addWidget(self.front_label, 0, 0, 1, 1)
        self.interior_label = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.interior_label.setFont(font)
        self.interior_label.setStyleSheet("#interior_label{background-color: #0CB90C;}")
        self.interior_label.setFrameShape(QtGui.QFrame.Box)
        self.interior_label.setAlignment(QtCore.Qt.AlignCenter)
        self.interior_label.setObjectName("interior_label")
        self.lightLayout.addWidget(self.interior_label, 0, 1, 1, 1)
        self.back_label = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.back_label.setFont(font)
        self.back_label.setStyleSheet("#back_label{background-color: #0CB90C;}")
        self.back_label.setFrameShape(QtGui.QFrame.Box)
        self.back_label.setAlignment(QtCore.Qt.AlignCenter)
        self.back_label.setObjectName("back_label")
        self.lightLayout.addWidget(self.back_label, 1, 0, 1, 1)
        self.reg_label = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.reg_label.setFont(font)
        self.reg_label.setStyleSheet("#reg_label{background-color: #0CB90C;}")
        self.reg_label.setFrameShape(QtGui.QFrame.Box)
        self.reg_label.setAlignment(QtCore.Qt.AlignCenter)
        self.reg_label.setObjectName("reg_label")
        self.lightLayout.addWidget(self.reg_label, 1, 1, 1, 1)
        lightView.setCentralWidget(self.mainWidgetLight)
        self.menubar = QtGui.QMenuBar(lightView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 654, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        lightView.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(lightView)
        QtCore.QMetaObject.connectSlotsByName(lightView)

    def retranslateUi(self, lightView):
        lightView.setWindowTitle(QtGui.QApplication.translate("lightView", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.front_label.setText(QtGui.QApplication.translate("lightView", "FRONT LIGHTS", None, QtGui.QApplication.UnicodeUTF8))
        self.interior_label.setText(QtGui.QApplication.translate("lightView", "INTERIOR LIGHT", None, QtGui.QApplication.UnicodeUTF8))
        self.back_label.setText(QtGui.QApplication.translate("lightView", "BACK LIGHTS", None, QtGui.QApplication.UnicodeUTF8))
        self.reg_label.setText(QtGui.QApplication.translate("lightView", "REGISTRATION PLATE", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("lightView", "File", None, QtGui.QApplication.UnicodeUTF8))

