# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Mathilde Theisen\Documents\NTNU\TDT4141 Programvareutvikling\sounds.ui'
#
# Created: Sat Apr 09 15:55:38 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(647, 435)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(0, -1, 50, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.soundLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(24)
        self.soundLabel.setFont(font)
        self.soundLabel.setObjectName("soundLabel")
        self.verticalLayout_5.addWidget(self.soundLabel)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setContentsMargins(50, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.allSoundsLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(16)
        self.allSoundsLabel.setFont(font)
        self.allSoundsLabel.setObjectName("allSoundsLabel")
        self.verticalLayout.addWidget(self.allSoundsLabel)
        self.allSoundsSlider = phonon.Phonon.VolumeSlider(self.centralwidget)
        self.allSoundsSlider.setObjectName("allSoundsSlider")
        self.verticalLayout.addWidget(self.allSoundsSlider)
        self.interiorLightLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(16)
        self.interiorLightLabel.setFont(font)
        self.interiorLightLabel.setObjectName("interiorLightLabel")
        self.verticalLayout.addWidget(self.interiorLightLabel)
        self.interiorLightSlider = phonon.Phonon.VolumeSlider(self.centralwidget)
        self.interiorLightSlider.setObjectName("interiorLightSlider")
        self.verticalLayout.addWidget(self.interiorLightSlider)
        self.toCloseLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(16)
        self.toCloseLabel.setFont(font)
        self.toCloseLabel.setObjectName("toCloseLabel")
        self.verticalLayout.addWidget(self.toCloseLabel)
        self.drivingToCloseSlider = phonon.Phonon.VolumeSlider(self.centralwidget)
        self.drivingToCloseSlider.setObjectName("drivingToCloseSlider")
        self.verticalLayout.addWidget(self.drivingToCloseSlider)
        self.blindZoneLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(16)
        self.blindZoneLabel.setFont(font)
        self.blindZoneLabel.setObjectName("blindZoneLabel")
        self.verticalLayout.addWidget(self.blindZoneLabel)
        self.blindZoneSlider = phonon.Phonon.VolumeSlider(self.centralwidget)
        self.blindZoneSlider.setObjectName("blindZoneSlider")
        self.verticalLayout.addWidget(self.blindZoneSlider)
        self.drivingToFastLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(16)
        self.drivingToFastLabel.setFont(font)
        self.drivingToFastLabel.setObjectName("drivingToFastLabel")
        self.verticalLayout.addWidget(self.drivingToFastLabel)
        self.drivingToFastSlider = phonon.Phonon.VolumeSlider(self.centralwidget)
        self.drivingToFastSlider.setObjectName("drivingToFastSlider")
        self.verticalLayout.addWidget(self.drivingToFastSlider)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 647, 21))
        self.menubar.setObjectName("menubar")
        self.menuLight_mode = QtGui.QMenu(self.menubar)
        self.menuLight_mode.setObjectName("menuLight_mode")
        self.menuSound = QtGui.QMenu(self.menubar)
        self.menuSound.setObjectName("menuSound")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSpeed_and_distance = QtGui.QAction(MainWindow)
        self.actionSpeed_and_distance.setObjectName("actionSpeed_and_distance")
        self.actionRecent_messages = QtGui.QAction(MainWindow)
        self.actionRecent_messages.setObjectName("actionRecent_messages")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuLight_mode.addAction(self.actionSpeed_and_distance)
        self.menuLight_mode.addAction(self.actionRecent_messages)
        self.menuLight_mode.addAction(self.actionQuit)
        self.menubar.addAction(self.menuLight_mode.menuAction())
        self.menubar.addAction(self.menuSound.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Code Red - Sound", None, QtGui.QApplication.UnicodeUTF8))
        self.soundLabel.setText(QtGui.QApplication.translate("MainWindow", "Sounds", None, QtGui.QApplication.UnicodeUTF8))
        self.allSoundsLabel.setText(QtGui.QApplication.translate("MainWindow", "All sounds", None, QtGui.QApplication.UnicodeUTF8))
        self.interiorLightLabel.setText(QtGui.QApplication.translate("MainWindow", "Interior light", None, QtGui.QApplication.UnicodeUTF8))
        self.toCloseLabel.setText(QtGui.QApplication.translate("MainWindow", "Driving to close to the car in front", None, QtGui.QApplication.UnicodeUTF8))
        self.blindZoneLabel.setText(QtGui.QApplication.translate("MainWindow", "Blindzone", None, QtGui.QApplication.UnicodeUTF8))
        self.drivingToFastLabel.setText(QtGui.QApplication.translate("MainWindow", "Driving to fast", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLight_mode.setTitle(QtGui.QApplication.translate("MainWindow", "Light mode", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSound.setTitle(QtGui.QApplication.translate("MainWindow", "Sound", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpeed_and_distance.setText(QtGui.QApplication.translate("MainWindow", "Speed and distance", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecent_messages.setText(QtGui.QApplication.translate("MainWindow", "Recent messages", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))

from PySide import phonon

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

